### ISSUE TITLE
How to get EarningsFlexUp?

### ISSUE THREAD

**Issue by rthorntn** [gurrier/localvolts#1]
Hi,

Sorry to bother you and thanks for this integration!

I installed via HACS.

I can see EarningsFlexUp in sensor.py but how do I expose this as an entity so I can track when to sell power?

Thanks again!

**Comment by gurrier** [comment]
It should be available as an entity called EarningsFlexUp 
Can you confirm if you can see "Localvolts" in the list of Integrations in Home assistant (after you've already added it in HACS first)?

**Comment by rthorntn** [comment]
Thanks for the very prompt reply, much appreciated!

I'm new to HASS.

The integration put a sensor on my dashboard called costsFlexUp and it's working.

I can see Localvolts as an integration.

Settings > Devices & Services > LocalVolts Integration shows:

0.1.0
Custom integration
Depends on the cloud
This integration was not set up from the UI
1 Entity, and if I click on the entity I get a table with one entry "costsFlexUp"

My About:
Core 2024.8.0
Supervisor 2024.08.0
Operating System 12.4
Frontend 20240806.1

**Comment by gurrier** [comment]
Correct.

This entity can be used in an automation now.
The value of that entity is the marginal cost of consuming an extra 1kWh of
energy in the next 5 minutes.

You may want to send a notification to your phone or announce it from a
smart speaker like Google Home or turn on a coloured light to adjust you
that the cost of electricity is very low.
Similarly you may use it as a trigger in an automation to curtail your
solar export if you can control your inverter via HASS.
Or if it indicates a high price in the market, you could use it as a
trigger to start exporting energy from a home battery.

**Comment by rthorntn** [comment]
Thanks!

Apologies, I might be confusing us here, I have costsFlexUp on my Dashboard and Automations but I also want EarningsFlexUp also and I cannot see EarningsFlexUp anywhere?

**Comment by gurrier** [comment]
Oh sorry. I misread.
I didn't actually expose that.
I'll look into it.

**Comment by gurrier** [comment]
> I have costsFlexUp on my Dashboard and Automations but I also want EarningsFlexUp

In reality I think it is a fairly predicatble outcome anyway.  The costs will be around 6c/kWh higher or thereabouts.
You can probably base your automations using the costFlexUp with that offset in mind in the meantime but I will look into it anyway.

**Comment by rthorntn** [comment]
Thanks, much appreciated, it would be brilliant to get an accurate earningsFlexUp.

It changes.  3-9pm during the eight ToU months is something like a 34c difference between buy and sell.  Outside of that its more like 9c.

**Comment by gurrier** [comment]
Try to gewt the latest version.
EarningsFlexUp has been added as a separate sensor

**Comment by rthorntn** [comment]
Thank you!
