### ISSUE TITLE
Can't Add Integration

### ISSUE THREAD

**Issue by danwnz** [gurrier/localvolts#5]
I am unable to add the integration successfully.
It will not accept my NMI (without the checksum) I also tried with it, just in case after 5 attempts.
It does seem to accept just numbers, but no data using that method all the values and attributes display unknown.

**Comment by gurrier** [comment]
Some thoughts.

Can you confirm that your NMI is 10 digits?

Have you requested access to the API from Localvolts and had confirmation that it was enabled?

**Comment by danwnz** [comment]
Hi,

Yes my NMI is 10 alpha numeric characters, it is not just digits.
Stars with QB followed by 8 digits.
Yes I have registered, and been provided the API and Partner ID.
Also I can confirm that the API, Partner ID and NMI are working with the
local volts API to retrieve data within another integration I was testing.

Regards,

Dan

**Comment by gurrier** [comment]
Can you try 0.4.2 latest release which has a fix for this issue.

**Comment by danwnz** [comment]
Hi,

Thank you so much for your quick response and fix.
It now works perfectly.

Regards,

Dan

**Comment by gurrier** [comment]
Great to hear.  It was a silly bug on my part.
Thanks for your help in reporting and confirming.
